### ISSUE TITLE
PackageBuildOutputs to create Delete Manifest records

### ISSUE THREAD

**Issue by dennis-behm** [IBM/dbb#265]
The PackageBuildOutputs is equipped to generate additional metadata for IBM Wazi Deploy.

To process deletions, the Wazi Deploy Application Manifest file needs to be extended and specify the `deleted_artifacts` artifacts like this:

```
deleted_artifacts:
- name: LGACDB02
  description: LGACDB02.CICSLOAD
  properties:
  - key: path
    value: NAZARE.WDEPLOY.DBBBUILD.GENAPP.LOAD/LGACDB02.CICSLOAD
  type: CICSLOAD
```
See: https://www.ibm.com/docs/en/developer-for-zos/16.0?topic=deployment-static-python-translator#wd_gettingstarted_static_python__delete_title
